require: sudo
language: node_js
services:
  - docker
env:
  - DOCKER_IMAGE=prodest/processoeletronico-api
script: 
  /bin/sh .travis.sh
deploy:
  - provider: script
     script: /bin/sh .develop.sh
     on:
       branch: develop
  - provider: script
     script: /bin/sh .hmg.sh
     on:
       branch: /^release-.*$/
