language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
services:
  - docker
env:
  - DOCKER_IMAGE=prodest/processoeletronico-api RANCHER_SERVICE_NAME=processoeletronico-api
script: 
  /bin/sh ./scripts/.travis.sh
deploy:
  - provider: script
    script: /bin/sh ./scripts/.develop.sh
    on:
      branch: develop
  - provider: script
    script: /bin/sh ./scripts/.release.sh
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^release.*$"
  - provider: script
    script: /bin/sh ./scripts/.master.sh
    on:
      branch: master
  - provider: script
    script: /bin/sh ./scripts/.demo.sh
    on:
      branch: demo
