require: sudo
language: node_js
services:
  - docker
env:
  - DOCKER_IMAGE=prodest/processoeletronico-api SERVICE_NAME=processoeletronico-api RANCHER_URL=http://cloud.datacenter.es.gov.br.local/v1/projects/1a10541 RANCHER_STACK=dev RANCHER_COMPOSE_URL=http://cloud.datacenter.es.gov.br.local/v1/projects/1a10541/environments/1e100/composeconfig
script: 
  /bin/sh .travis.sh
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh .develop.sh
  on:
    branch: develop
