language: csharp
dist: trusty
mono: none
dotnet: 1.0.4
services:
  - docker
install:
  - nvm install 6.10
script: 
  - scripts/travis.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh api dev ${TRAVIS_COMMIT:0:7} # && scripts/deploy.sh app dev ${TRAVIS_COMMIT:0:7}
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh api hmg $TRAVIS_TAG
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^api-v\d+\.\d+\.\d+-rc\d+$"

  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh app hmg $TRAVIS_TAG
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^app-v\d+\.\d+\.\d+-rc\d+$"

  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh api prd $TRAVIS_TAG
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^api-v\d+\.\d+\.\d+$"

  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh app prd $TRAVIS_TAG
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_TAG =~ ^app-v\d+\.\d+\.\d+$"

  - provider: script
    skip_cleanup: true
    script: scripts/deploy.sh api demo ${TRAVIS_COMMIT:0:7}
    on:
      branch: demo
